/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoBlogRouteImport } from './routes/video-blog'
import { Route as NoticeRouteImport } from './routes/notice'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRoutinesRouteImport } from './routes/admin.routines'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminPreviewRouteImport } from './routes/admin.preview'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminAdmissionsRouteImport } from './routes/admin.admissions'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminAboutRouteImport } from './routes/admin.about'

const VideoBlogRoute = VideoBlogRouteImport.update({
  id: '/video-blog',
  path: '/video-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeRoute = NoticeRouteImport.update({
  id: '/notice',
  path: '/notice',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoutinesRoute = AdminRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/notice': typeof NoticeRoute
  '/video-blog': typeof VideoBlogRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/routines': typeof AdminRoutinesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/notice': typeof NoticeRoute
  '/video-blog': typeof VideoBlogRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/routines': typeof AdminRoutinesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/notice': typeof NoticeRoute
  '/video-blog': typeof VideoBlogRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/routines': typeof AdminRoutinesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admission'
    | '/auth'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/notice'
    | '/video-blog'
    | '/admin/about'
    | '/admin/admins'
    | '/admin/admissions'
    | '/admin/blogs'
    | '/admin/courses'
    | '/admin/gallery'
    | '/admin/home'
    | '/admin/notices'
    | '/admin/preview'
    | '/admin/results'
    | '/admin/routines'
    | '/admin/settings'
    | '/admin/videos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admission'
    | '/auth'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/notice'
    | '/video-blog'
    | '/admin/about'
    | '/admin/admins'
    | '/admin/admissions'
    | '/admin/blogs'
    | '/admin/courses'
    | '/admin/gallery'
    | '/admin/home'
    | '/admin/notices'
    | '/admin/preview'
    | '/admin/results'
    | '/admin/routines'
    | '/admin/settings'
    | '/admin/videos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admission'
    | '/auth'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/notice'
    | '/video-blog'
    | '/admin/about'
    | '/admin/admins'
    | '/admin/admissions'
    | '/admin/blogs'
    | '/admin/courses'
    | '/admin/gallery'
    | '/admin/home'
    | '/admin/notices'
    | '/admin/preview'
    | '/admin/results'
    | '/admin/routines'
    | '/admin/settings'
    | '/admin/videos'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdmissionRoute: typeof AdmissionRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  NoticeRoute: typeof NoticeRoute
  VideoBlogRoute: typeof VideoBlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-blog': {
      id: '/video-blog'
      path: '/video-blog'
      fullPath: '/video-blog'
      preLoaderRoute: typeof VideoBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice': {
      id: '/notice'
      path: '/notice'
      fullPath: '/notice'
      preLoaderRoute: typeof NoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/routines': {
      id: '/admin/routines'
      path: '/routines'
      fullPath: '/admin/routines'
      preLoaderRoute: typeof AdminRoutinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preview': {
      id: '/admin/preview'
      path: '/preview'
      fullPath: '/admin/preview'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAdmissionsRoute: typeof AdminAdmissionsRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminPreviewRoute: typeof AdminPreviewRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminRoutinesRoute: typeof AdminRoutinesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAdmissionsRoute: AdminAdmissionsRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminPreviewRoute: AdminPreviewRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminRoutinesRoute: AdminRoutinesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdmissionRoute: AdmissionRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  NoticeRoute: NoticeRoute,
  VideoBlogRoute: VideoBlogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
